name: build image

on:
  push:
  branches: [ example ]

jobs:

  build:
      runs-on: ubuntu-latest

      steps:

        - name: checkout
          uses: actions/checkout@v5
        
        - name: configurar python
          uses: actions/setup-python@v5
          with:
            python-version: '3.10'
          
        - name: Instalar dependencias
          run: pip install flask

        - name: Ejecutar las pruebas unitarias
          run: python test.py

        - name: login a GitHub Packages
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN}}

        - name: Construir y publicar la imagen
          uses: docker/build-push-action@v4
          with:
            context: .
            push: true
            tags: ghcr.io/${{ github.repository_owner}}/python_app:latest